{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
{{- end }}
